---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clutch-cvd-pvc
  namespace: fraxses-clutchhealth
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi